name: Publish

on:
  push:
    branches:
    - main
    tags:
    - '!*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Check Release
      id: check-release
      run: |
        tag="$(git describe --tags --exact-match 2> /dev/null || :)"
        if [[ -z "$tag" ]];
          then
            echo "::set-output name=IS_RELEASE::false"
          else
            echo "::set-output name=IS_RELEASE::true"
        fi
    - name: Setup Go
      if: ${{ steps.check-release.outputs.IS_RELEASE == 'true' }}
      uses: actions/setup-go@v2
      with:
        go-version: '1.13.15'
    - name: Setup Node
      if: ${{ steps.check-release.outputs.IS_RELEASE == 'true' }}
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install
      if: ${{ steps.check-release.outputs.IS_RELEASE == 'true' }}
      run: yarn install --check-files --frozen-lockfile --network-timeout 1000000
    - name: Build
      if: ${{ steps.check-release.outputs.IS_RELEASE == 'true' }}
      run: yarn build
      env:
        GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    - name: Publish
      if: ${{ steps.check-release.outputs.IS_RELEASE == 'true' }}
      run: yarn publish-from-github
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN_ELEVATED }}
        GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
