name: Publish

on:
  push:
    branches:
    - master
    tags:
    - '!*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '1.13.15'
    - uses: actions/setup-node@v2
      with:
        node-version: 12
    - uses: actions/checkout@v1
    - name: Install
      run: yarn install --check-files --frozen-lockfile --network-timeout 1000000
    - name: Build
      run: yarn build
      env:
        GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    - name: Publish
      run: yarn publish-from-github
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
