name: Unit

on:
  push:
    branches:
    - main
    tags:
    - '!*'
  pull_request:

jobs:
  test:
    name: Unit
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Conditionally set remote env
        if: github.event.pull_request.head.repo.full_name == github.repository
        run: |
            echo "TURBO_REMOTE_ONLY=true" >> $GITHUB_ENV
            echo "TURBO_TEAM=vercel" >> $GITHUB_ENV
            echo "TURBO_TOKEN=${{ secrets.TURBO_TOKEN }}" >> $GITHUB_ENV
      - uses: actions/setup-go@v2
        with:
          go-version: '1.13.15'
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - run: git --version
      - run: git fetch origin main --depth=100
      - run: git fetch origin ${{ github.ref }} --depth=100
      - run: git diff origin/main...HEAD --name-only
      - run: yarn install --network-timeout 1000000
      - run: yarn run build
      - run: yarn run lint
        if: matrix.os == 'ubuntu-latest' && matrix.node == 14 # only run lint once
      - run: yarn run test-unit
      - run: yarn workspace vercel run coverage
        if: matrix.os == 'ubuntu-latest' && matrix.node == 14 # only run coverage once
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
