name: CLI

on:
  push:
    branches:
    - main
    tags:
    - '!*'
  pull_request:

jobs:
  test:
    name: CLI
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Conditionally set remote env
        if: github.event.pull_request.head.repo.full_name == github.repository
        run: |
            echo "TURBO_REMOTE_ONLY=true" >> $GITHUB_ENV
            echo "TURBO_TEAM=vercel" >> $GITHUB_ENV
            echo "TURBO_TOKEN=${{ secrets.TURBO_TOKEN }}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.13.15'
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn install --network-timeout 1000000 --frozen-lockfile
      - run: yarn run build
      - run: yarn test-integration-cli
        env:
          VERCEL_TEAM_TOKEN: ${{ secrets.VERCEL_TEAM_TOKEN }}
          VERCEL_REGISTRATION_URL: ${{ secrets.VERCEL_REGISTRATION_URL }}
