name: Tests

on:
  push:
    branches:
    - main
    tags:
    - '!*'
  pull_request:

env:
  NODE_VERSION: '14'

jobs:
  setup:
    name: Find Changes
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps['set-tests'].outputs['tests'] }}
    steps:
      - uses: actions/checkout@v2
      - run: git --version
      - run: git fetch origin main
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
      - run: yarn install --network-timeout 1000000

      - id: set-tests
        run: |
          TESTS_ARRAY=$(node utils/chunk-tests.js $SCRIPT_NAME)
          echo "Files to test:"
          echo "$TESTS_ARRAY"
          echo "::set-output name=tests::$TESTS_ARRAY"

  test:
    timeout-minutes: 120
    runs-on: ${{ matrix.runner }}
    name: ${{matrix.scriptName}} (${{matrix.packageName}}, ${{matrix.chunkNumber}}, ${{ matrix.runner }})
    if: ${{ needs.setup.outputs['tests'] != '[]' }}
    env:
      TURBO_REMOTE_ONLY: true
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    needs:
      - setup
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.setup.outputs['tests']) }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.13.15'
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
      - run: yarn install --network-timeout 1000000

      - name: Build ${{matrix.packageName}} and all its dependencies
        run: yarn turbo run build --cache-dir=".turbo" --scope=${{matrix.packageName}} --include-dependencies --no-deps
        env:
          FORCE_COLOR: '1'
      - name: Test ${{matrix.packageName}}
        run: node_modules/.bin/turbo run test --cache-dir=".turbo" --scope=${{matrix.packageName}} --no-deps -- ${{ join(matrix.testPaths, ' ') }}
        shell: bash
        env:
          VERCEL_TEAM_TOKEN: ${{ secrets.VERCEL_TEAM_TOKEN }}
          VERCEL_REGISTRATION_URL: ${{ secrets.VERCEL_REGISTRATION_URL }}
          FORCE_COLOR: '1'

  conclusion:
    needs:
      - test
    runs-on: ubuntu-latest
    name: E2E
    steps:
      - name: Done
        run: echo "Done."
