name: CLI

on:
  push:
    branches:
    - main
    tags:
    - '!*'
  pull_request:

env:
  TURBO_REMOTE_ONLY: 'true'
  TURBO_TEAM: 'vercel'
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    name: CLI
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.13.15'
      - uses: actions/setup-node@v3
        timeout-minutes: 5 # See https://github.com/actions/cache/issues/810
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn install --network-timeout 1000000 --frozen-lockfile
      - run: yarn run build
      - run: yarn test-integration-cli
        env:
          VERCEL_TEST_TOKEN: ${{ secrets.VERCEL_TEST_TOKEN }}
          VERCEL_TEST_REGISTRATION_URL: ${{ secrets.VERCEL_TEST_REGISTRATION_URL }}
