name: CLI

on:
  push:
    branches:
    - main
    tags:
    - '!*'
  pull_request:

jobs:
  test:
    name: CLI
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [14]
    runs-on: ${{ matrix.os }}
    env:
      TURBO_REMOTE_ONLY: true
      TURBO_TEAM: vercel
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.13.15'
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - run: git --version
      - run: git fetch origin main --depth=100
      - run: git fetch origin ${{ github.ref }} --depth=100
      - run: git diff origin/main...HEAD --name-only
      - run: yarn install --network-timeout 1000000
      - run: yarn run build
      - run: yarn test-integration-cli
        env:
          VERCEL_TEAM_TOKEN: ${{ secrets.VERCEL_TEAM_TOKEN }}
          VERCEL_REGISTRATION_URL: ${{ secrets.VERCEL_REGISTRATION_URL }}
